package com.yjy.wallet.bean.tokenview

data class TTx(val blockHash: String = "",
               val inputData: String = "",
               val fee: String = "",
               val index: Int = 0,
               val txid: String = "",
               val type: String = "",
               val confirmations: Int = 0,
               val nonce: Int = 0,
               val network: String = "",
               val blockNo: Int = 0,
               val toIsContract: Int = 0,
               val gasLimit: Int = 0,
               val gasUsed: Int = 0,
               val tokenTransfer: List<TokenTransferItem>?,
               var txs: List<TUTx>?,
               val from: String = "",
               val time: Long = 0,
               val to: String = "",
               val value: String = "",
               var traceErr: String = "",
               var receiptErr: String = "",
               val height: Int = 0,
               val gasPrice: Long = 0)